### ISSUE TITLE
Add daily CI jobs to all our repositories

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4072]
A recent change to Singular_jll broke Singular.jl but that's not visible at https://github.com/oscar-system/Singular.jl/actions because the CI there run the last time two weeks ago.

In general it can happen that a package breaks due to changes in one of its dependencies.

Thus I think we should set up our repositories to ensure that the CI jobs are run at least once a day.

E.g. in GAP we do that, see https://github.com/gap-system/gap/blob/master/.github/workflows/CI.yml by adding this to the `on:` trigger in the YAML file of the relevant job:
```YAML
  schedule:
    # Every day at 2:30 AM UTC
    - cron: '30 2 * * *'
```
