### ISSUE TITLE
oscar needs speed regression tests

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Oscar.jl#697]
candlesticks. Changes to one part of the system can have huge unintended performance consequences for other parts of the system. We need a set S of examples to run to check for regressions every so often. If we get a situation of the form "I added feature X to part Y, but this slowed down S by more than 2x", then we can say the performance regression needs to be addressed before X is added.

**Comment by fingolfin** [comment]
@aaruni96 we've discuss this before, it's yet another thing I'd like us to take care of at some point...

Some thoughts:
- we need a machine on which we can run these tests which is otherwise not under heavy load... That makes it a bit problematic to use our regular CI servers. Perhaps we could use `munk` (an Apple Mac Mini M1 we sometimes use for debugging, but probably not at, say, 3:00 in the night)
- https://github.com/MilesCranmer/AirspeedVelocity.jl sounds useful
- https://github.com/python/codespeed/ might be useful as a web frontend (its master is from 5 years ago but it has active branches driving e.g. https://speed.pypy.org
- but of course one probably also use Grafana or other tools
- - we need to select a list of "benchmarks". While we could use the entire test suite, that might not be ideal, and those two have somewhat different goals... That said, we gotta start somewhere, and at the beginning one could just use a few hand curated benchmarks
- similar setups for our other packages might be useful to have as well!

**Comment by fingolfin** [comment]
Julia now has [a page tracking timings](https://juliaci.github.io/julia-ci-timing/?s=lb.lt.lc.mb.mt.mc.wb.wt.wc.fb.ft&x=1764703618406.1767903618406&y=-3245.39965&l=7), see also <https://github.com/JuliaCI/julia-ci-timing>, perhaps we can borrow from that?

**Comment by aaruni96** [comment]
Looking into julia-ci-timing, it looks to be something like an overly complicated HTML file reading data from a yaml file.

The yaml file roughly needs to  look like the following, and then their data can be swapped out for data we want to display:

```yml
{
    "generated_at": "2026-01-21T14:22:35Z",
    "jobs": {
        ":linux: test 1.12 short": {
            "recent": [
                    {
                        "agent": "blah",
                        "author": "blah",
                        "build": 55567,
                        "commit": "54f3afd",
                        "duration": 500,
                        "message": "stuff",
                        "pipeline": "master",
                        "retry": 0,
                        "state": "passed",
                        "date": "2026-01-21 05:44"

                    },
                    {
                        "agent": "blah",
                        "author": "blah",
                        "build": 55565,
                        "commit": "54f3a69",
                        "duration": 3141,
                        "message": "stuff",
                        "pipeline": "master",
                        "retry": 0,
                        "state": "passed",
                        "date": "2026-01-20 05:44"

                    },
                    {
                        "agent": "blah",
                        "author": "blah",
                        "build": 55565,
                        "commit": "54f3aa9",
                        "duration": 300,
                        "message": "stuff",
                        "pipeline": "master",
                        "retry": 0,
                        "state": "passed",
                        "date": "2026-01-19 05:44"

                    }
                ],
                "stats": {
                    "count": 3,
                    "max_seconds": 3141,
                    "min_seconds": 300,
                    "mean_seconds": 2000,
                    "median_seconds": 2222,
                    "std_seconds": 35
                }
        }
    }
}

```

So, for every "test" we want to track, we want a small object which has timestamp, runtime, and some other metadata. We also want to update the `stats` entry at the end.

Questions

- I guess this means, for every workflow in our CI run, we generate 298 separate "tests" to keep a track of ?
- Do we also want to keep track of how long it took the workflow to run in total?
